on:
  workflow_call:
    inputs:
      build_runner:
        required: true
        type: string
      e2e_test_runner:
        required: false
        type: string
      target_triple:
        required: true
        type: string
      do_e2e_tests:
        required: true
        type: boolean
      use_cachix:
        required: true
        type: boolean
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

env:
  nix_target: ".#caligula-${{ inputs.target_triple }}"
  artifact: "caligula-${{ inputs.target_triple }}"

jobs:
  build:
    name: "Build using Nix"
    runs-on: ${{ inputs.build_runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = ${{ inputs.target_triple }}
            system-features = kvm benchmark big-parallel nixos-test uid-range

      - uses: cachix/cachix-action@v14
        if: ${{ inputs.use_cachix }}
        with:
          name: astralbijection
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build ${{ env.nix_target }} --show-trace --log-lines 10000 --fallback

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact }}
          path: result/bin/caligula

      - name: Run checks
        if: inputs.do_e2e_tests
        run: nix flake check --keep-going

  e2e-test-fresh:
    name: e2e test on fresh ${{ inputs.e2e_test_runner }}
    runs-on: ${{ inputs.e2e_test_runner }}
    needs: build
    if: inputs.do_e2e_tests

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ env.artifact }}

    - name: Set permissions on artifact
      run: chmod +x caligula

    - name: Ensure the command runs
      run: ./caligula --help
