name: "CI"

on:
  push:
  pull_request:
  pull_request_target:

jobs:
  lint:
    name: Run formatting and linting checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = ${{ inputs.target_triple }}

      - name: Prefetch lint script dependencies
        run: nix build .#lint-script

      - name: Run lint script
        run: nix run .#lint-script

  ci-x86_64-linux:
    uses: ./.github/workflows/ci-unix.yml
    with:
      build_runner: ubuntu-latest
      e2e_test_runner: ubuntu-latest
      target_triple: x86_64-linux
      do_e2e_tests: true
      use_cachix: ${{ github.event_name == 'push' }}
    secrets: inherit

  ci-x86_64-darwin:
    uses: ./.github/workflows/ci-unix.yml
    with:
      build_runner: macos-13
      e2e_test_runner: macos-13
      target_triple: x86_64-darwin
      do_e2e_tests: true
      use_cachix: ${{ github.event_name == 'push' }}
    secrets: inherit

  ci-aarch64-linux:
    uses: ./.github/workflows/ci-unix.yml
    with:
      build_runner: ubuntu-latest
      target_triple: aarch64-linux
      do_e2e_tests: false
      use_cachix: ${{ github.event_name == 'push' }}
    secrets: inherit

  ci-aarch64-darwin:
    uses: ./.github/workflows/ci-unix.yml
    with:
      build_runner: macos-latest
      e2e_test_runner: macos-latest
      target_triple: aarch64-darwin
      do_e2e_tests: true
      use_cachix: ${{ github.event_name == 'push' }}
    secrets: inherit

  ci-devshell:
    strategy:
      matrix:
        include:
          - runner: macos-latest
            platform: x86_64-darwin
          - runner: ubuntu-latest
            platform: x86_64-linux
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        if: ${{ github.event_name == 'push' }}
        with:
          name: astralbijection
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build dev shell
        run: nix build .#devShells.${{ matrix.platform }}.default --show-trace --log-lines 10000 --fallback

  make-release-group:
    runs-on: ubuntu-latest
    needs:
      - ci-aarch64-darwin
      - ci-aarch64-linux
      - ci-x86_64-darwin
      - ci-x86_64-linux
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Assemble release directory
        run: |
          mkdir release
          for i in caligula-*; do
            cp "$i/caligula" "release/$i"
          done

          tree

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: release
